import './globals.css'


export const metadata = {
  title: 'Play Right App',
  description: 'Generated by Gideon Okai Boateng',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
